add_test( [==[4-bit pack/unpack round-trip]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_packing [==[4-bit pack/unpack round-trip]==]  )
set_tests_properties( [==[4-bit pack/unpack round-trip]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[2-bit pack/unpack round-trip]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_packing [==[2-bit pack/unpack round-trip]==]  )
set_tests_properties( [==[2-bit pack/unpack round-trip]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[3-bit pack/unpack round-trip (padded must be mult of 8)]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_packing [==[3-bit pack/unpack round-trip (padded must be mult of 8)]==]  )
set_tests_properties( [==[3-bit pack/unpack round-trip (padded must be mult of 8)]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[Unpacked indices are in [0, 2^bits-1]]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_packing [==[Unpacked indices are in \[0\, 2^bits-1\]]==]  )
set_tests_properties( [==[Unpacked indices are in [0, 2^bits-1]]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[Quantizer quantize/dequantize MSE within expected bounds]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_packing [==[Quantizer quantize/dequantize MSE within expected bounds]==]  )
set_tests_properties( [==[Quantizer quantize/dequantize MSE within expected bounds]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
set( test_packing_TESTS [==[4-bit pack/unpack round-trip]==] [==[2-bit pack/unpack round-trip]==] [==[3-bit pack/unpack round-trip (padded must be mult of 8)]==] [==[Unpacked indices are in [0, 2^bits-1]]==] [==[Quantizer quantize/dequantize MSE within expected bounds]==])
