add_test( [==[next_pow2 returns correct values]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_fwht [==[next_pow2 returns correct values]==]  )
set_tests_properties( [==[next_pow2 returns correct values]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[gen_rademacher produces only +/-1]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_fwht [==[gen_rademacher produces only +/-1]==]  )
set_tests_properties( [==[gen_rademacher produces only +/-1]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[gen_rademacher is seed-deterministic]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_fwht [==[gen_rademacher is seed-deterministic]==]  )
set_tests_properties( [==[gen_rademacher is seed-deterministic]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[gen_rademacher differs across seeds]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_fwht [==[gen_rademacher differs across seeds]==]  )
set_tests_properties( [==[gen_rademacher differs across seeds]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[FWHT round-trip MSE < 1e-10 for common head dims]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_fwht [==[FWHT round-trip MSE < 1e-10 for common head dims]==]  )
set_tests_properties( [==[FWHT round-trip MSE < 1e-10 for common head dims]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[FWHT round-trip for non-power-of-2 dims (padding path)]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_fwht [==[FWHT round-trip for non-power-of-2 dims (padding path)]==]  )
set_tests_properties( [==[FWHT round-trip for non-power-of-2 dims (padding path)]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[FWHT is linear: forward(a+b) == forward(a)+forward(b)]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_fwht [==[FWHT is linear: forward(a+b) == forward(a)+forward(b)]==]  )
set_tests_properties( [==[FWHT is linear: forward(a+b) == forward(a)+forward(b)]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
set( test_fwht_TESTS [==[next_pow2 returns correct values]==] [==[gen_rademacher produces only +/-1]==] [==[gen_rademacher is seed-deterministic]==] [==[gen_rademacher differs across seeds]==] [==[FWHT round-trip MSE < 1e-10 for common head dims]==] [==[FWHT round-trip for non-power-of-2 dims (padding path)]==] [==[FWHT is linear: forward(a+b) == forward(a)+forward(b)]==])
