if(EXISTS "/mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api-b12d07c_tests.cmake")
  include("/mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api-b12d07c_tests.cmake")
else()
  add_test(test_api_NOT_BUILT-b12d07c test_api_NOT_BUILT-b12d07c)
endif()
