add_test( [==[ContiguousSlabStorage: write/read round-trip]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[ContiguousSlabStorage: write/read round-trip]==]  )
set_tests_properties( [==[ContiguousSlabStorage: write/read round-trip]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[ContiguousSlabStorage: ring eviction at capacity]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[ContiguousSlabStorage: ring eviction at capacity]==]  )
set_tests_properties( [==[ContiguousSlabStorage: ring eviction at capacity]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[ContiguousSlabStorage: reset zeroes size]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[ContiguousSlabStorage: reset zeroes size]==]  )
set_tests_properties( [==[ContiguousSlabStorage: reset zeroes size]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[ContiguousSlabStorage: bytes_used tracks written data]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[ContiguousSlabStorage: bytes_used tracks written data]==]  )
set_tests_properties( [==[ContiguousSlabStorage: bytes_used tracks written data]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[SegmentedSlabStorage: write/read round-trip single tag]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[SegmentedSlabStorage: write/read round-trip single tag]==]  )
set_tests_properties( [==[SegmentedSlabStorage: write/read round-trip single tag]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[SegmentedSlabStorage: multiple format_tags are independent]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[SegmentedSlabStorage: multiple format_tags are independent]==]  )
set_tests_properties( [==[SegmentedSlabStorage: multiple format_tags are independent]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[SegmentedSlabStorage: reset clears all slabs]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[SegmentedSlabStorage: reset clears all slabs]==]  )
set_tests_properties( [==[SegmentedSlabStorage: reset clears all slabs]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[Contract: ContiguousSlabStorage]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[Contract: ContiguousSlabStorage]==]  )
set_tests_properties( [==[Contract: ContiguousSlabStorage]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[Contract: SegmentedSlabStorage]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_storage [==[Contract: SegmentedSlabStorage]==]  )
set_tests_properties( [==[Contract: SegmentedSlabStorage]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
set( test_storage_TESTS [==[ContiguousSlabStorage: write/read round-trip]==] [==[ContiguousSlabStorage: ring eviction at capacity]==] [==[ContiguousSlabStorage: reset zeroes size]==] [==[ContiguousSlabStorage: bytes_used tracks written data]==] [==[SegmentedSlabStorage: write/read round-trip single tag]==] [==[SegmentedSlabStorage: multiple format_tags are independent]==] [==[SegmentedSlabStorage: reset clears all slabs]==] [==[Contract: ContiguousSlabStorage]==] [==[Contract: SegmentedSlabStorage]==])
