if(EXISTS "/mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_conformance-b12d07c_tests.cmake")
  include("/mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_conformance-b12d07c_tests.cmake")
else()
  add_test(test_conformance_NOT_BUILT-b12d07c test_conformance_NOT_BUILT-b12d07c)
endif()
