add_test( [==[adaptq_create returns non-null handle]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_create returns non-null handle]==]  )
set_tests_properties( [==[adaptq_create returns non-null handle]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_last_error is empty after successful create]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_last_error is empty after successful create]==]  )
set_tests_properties( [==[adaptq_last_error is empty after successful create]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_kv_bytes is 0 before any append]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_kv_bytes is 0 before any append]==]  )
set_tests_properties( [==[adaptq_kv_bytes is 0 before any append]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_append increases kv_bytes]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_append increases kv_bytes]==]  )
set_tests_properties( [==[adaptq_append increases kv_bytes]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_compute returns active token count]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_compute returns active token count]==]  )
set_tests_properties( [==[adaptq_compute returns active token count]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_compute output is non-zero after append]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_compute output is non-zero after append]==]  )
set_tests_properties( [==[adaptq_compute output is non-zero after append]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_compute on empty cache returns 0]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_compute on empty cache returns 0]==]  )
set_tests_properties( [==[adaptq_compute on empty cache returns 0]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_reset zeroes cache]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_reset zeroes cache]==]  )
set_tests_properties( [==[adaptq_reset zeroes cache]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_mha_create / destroy]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_mha_create / destroy]==]  )
set_tests_properties( [==[adaptq_mha_create / destroy]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_mha_append + compute basic contract]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_mha_append + compute basic contract]==]  )
set_tests_properties( [==[adaptq_mha_append + compute basic contract]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_mha_append: out-of-range head_idx sets error]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_mha_append: out-of-range head_idx sets error]==]  )
set_tests_properties( [==[adaptq_mha_append: out-of-range head_idx sets error]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_mha_compute: out-of-range head_idx returns -1]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_mha_compute: out-of-range head_idx returns -1]==]  )
set_tests_properties( [==[adaptq_mha_compute: out-of-range head_idx returns -1]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_mha_reset clears all heads]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_mha_reset clears all heads]==]  )
set_tests_properties( [==[adaptq_mha_reset clears all heads]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_version returns non-empty string]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_version returns non-empty string]==]  )
set_tests_properties( [==[adaptq_version returns non-empty string]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
add_test( [==[adaptq_features returns valid bitmask]==] /mnt/e/Researches/AdaptQ/adapTQ/build_wsl/test_api [==[adaptq_features returns valid bitmask]==]  )
set_tests_properties( [==[adaptq_features returns valid bitmask]==] PROPERTIES WORKING_DIRECTORY /mnt/e/Researches/AdaptQ/adapTQ/build_wsl SKIP_RETURN_CODE 4)
set( test_api_TESTS [==[adaptq_create returns non-null handle]==] [==[adaptq_last_error is empty after successful create]==] [==[adaptq_kv_bytes is 0 before any append]==] [==[adaptq_append increases kv_bytes]==] [==[adaptq_compute returns active token count]==] [==[adaptq_compute output is non-zero after append]==] [==[adaptq_compute on empty cache returns 0]==] [==[adaptq_reset zeroes cache]==] [==[adaptq_mha_create / destroy]==] [==[adaptq_mha_append + compute basic contract]==] [==[adaptq_mha_append: out-of-range head_idx sets error]==] [==[adaptq_mha_compute: out-of-range head_idx returns -1]==] [==[adaptq_mha_reset clears all heads]==] [==[adaptq_version returns non-empty string]==] [==[adaptq_features returns valid bitmask]==])
